dist: bionic
language: cpp
compiler: gcc
addons:
  apt:
    packages:
      - gcc-8
      - g++-8
script:
- mkdir build
- cd build
- cmake ..
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T ip_filter-0.0.1-Linux.deb -uboogermann:$BINTRAY_API_KEY "https://api.bintray.com/content/home-office/otus-cpp/ip_filter/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.1-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"